[package]
name = "file-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.83"
rocket = { version = "0.5.0-rc.2", features = ["json"] }
sqlite = "0.30.3"